# Generated by Django 5.2.9 on 2025-12-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divine_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('service', models.CharField(choices=[('Hair Cut', 'Hair Cut'), ('Facial', 'Facial'), ('Massage', 'Massage')], max_length=50)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('preferred_date', 'preferred_time'), name='unique_appointment_slot')],
            },
        ),
    ]
