# Generated by Django 5.2.9 on 2025-12-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divine_app', '0003_service_alter_appointment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/%Y/%m/%d'),
        ),
    ]
