# Generated by Django 5.2.9 on 2025-12-22 09:09

import divine_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divine_app', '0004_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[divine_app.validators.max_20_words]),
        ),
    ]
