# Generated by Django 5.2.9 on 2026-01-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divine_app', '0007_feedbackform_alter_userprofile_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBackForm',
            new_name='FeedBack',
        ),
    ]
